from enum import Enum

class JobType(str, Enum):
    TEST_JOB = "TEST_JOB"
    CSV_ROW_COUNT = "CSV_ROW_COUNT"
    CSV_COLUMN_STATS = "CSV_COLUMN_STATS"
    CSV_DEDUPLICATE = "CSV_DEDUPLICATE"
    JSON_CANONICALIZE = "JSON_CANONICALIZE"
