"""phase4 retry scheduling fields

Revision ID: 38348c36b202
Revises: c83d02a2515c
Create Date: 2026-01-23 16:01:24.070996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38348c36b202'
down_revision: Union[str, Sequence[str], None] = 'c83d02a2515c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('next_run_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('jobs', sa.Column('finished_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.create_index('ix_jobs_status_next_run_at', 'jobs', ['status', 'next_run_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_jobs_status_next_run_at', table_name='jobs')
    op.drop_column('jobs', 'finished_at')
    op.drop_column('jobs', 'next_run_at')
    # ### end Alembic commands ###
