"""add job_type and input_metadata

Revision ID: 73f2e42874bc
Revises: 38348c36b202
Create Date: 2026-01-25 15:13:39.513950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '73f2e42874bc'
down_revision: Union[str, Sequence[str], None] = '38348c36b202'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    job_type_enum = sa.Enum('TEST_JOB', 'CSV_ROW_COUNT', 'CSV_COLUMN_STATS', 'CSV_DEDUPLICATE', 'JSON_CANONICALIZE', name='job_type')
    job_type_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('jobs', sa.Column('job_type', job_type_enum, nullable=False))
    op.add_column('jobs', sa.Column('input_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.create_index('ix_jobs_job_type', 'jobs', ['job_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_jobs_job_type', table_name='jobs')
    op.drop_column('jobs', 'input_metadata')
    op.drop_column('jobs', 'job_type')
    sa.Enum(name='job_type').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
