"""add job constraints and indexes

Revision ID: c83d02a2515c
Revises: 332b6465002f
Create Date: 2026-01-10 13:11:33.112593

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c83d02a2515c'
down_revision: Union[str, Sequence[str], None] = '332b6465002f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_jobs_status_created_at', 'jobs', ['status', 'created_at'], unique=False)
    op.create_index('ix_jobs_user_id_created_at', 'jobs', ['user_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_jobs_user_id_created_at', table_name='jobs')
    op.drop_index('ix_jobs_status_created_at', table_name='jobs')
    # ### end Alembic commands ###
