"""Add context and remove user

Revision ID: f4457f8e8b3f
Revises: 73f2e42874bc
Create Date: 2026-02-05 16:57:22.172719

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f4457f8e8b3f'
down_revision: Union[str, Sequence[str], None] = '73f2e42874bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.add_column('jobs', sa.Column('notifications', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.alter_column('jobs', 'next_run_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=True)
    op.alter_column('jobs', 'finished_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=True)
    op.drop_index(op.f('ix_jobs_user_id_created_at'), table_name='jobs')
    op.drop_column('jobs', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_jobs_user_id_created_at'), 'jobs', ['user_id', 'created_at'], unique=False)
    op.alter_column('jobs', 'finished_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('jobs', 'next_run_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.drop_column('jobs', 'notifications')
    op.drop_column('jobs', 'context')
    # ### end Alembic commands ###
